### ISSUE TITLE
Create initial DB models and migrations

### ISSUE THREAD

**Issue by ricco386** [pyconsk/django-konfera#1]
All models should have, created, modified datetime fields, that are updated automatically. 
If there is status, it should have status_modified field updated automatically. 

List of issues to be done in order to have initial DB schema

Tables that doesnt have FK, so they can be created first:

- [x] #3 Create location model
- [x] #13 Create receipt model
- [x] #8 Create room model

****

Models required for event management, should be created afterwards:

- [x] #2 Create events model
- [x] #4 Create sponsor model 
- [x] #5 Create speaker model 
- [x] #6 Create talk model
- [x] #7 Create schedule model

****

Models for receipts and billing, should be create lastly

- [x] #9 Create tycket_type model
- [x] #12 Create order model
- [x] #11 Create discount_codes model
- [x] #10 Create Ticket (Atendee) model

****

Once all done create initial migration.

- [x] generate initial migration

Django Documentation: https://docs.djangoproject.com/en/1.10/topics/db/models/

**Comment by ZoltanOnody** [comment]
working on it
